ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 800
TOTAL_LEVELS = 27

# enemy constants
SPAWN_COOLDOWN = 400


# turrent constants
TURRET_LEVELS = 4
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 10
LEVEL_CONMPLTE_REWARD = 150
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 5
